AIR_QUALITY_API_KEY = "1e280114-e404-4dd7-b54b-eefcabad1bc1"

KAKAO_API_KEY = "995b87d61cdf42266686c299c3bdce51"
KAKAO_REST_API_KEY = "995b87d61cdf42266686c299c3bdce51"
REDIRECT_URI = "http://localhost:8501"
KAKAO_CHANNEL_PUBLIC_ID = "_xfxhjXn"

SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"



